stages:
  - test
  - deploy

test-framework:
  stage: test
  image: maven:3.6.0-jdk-8-alpine
  services:
  - redis:5.0.3
  before_script:
    # proxy settings
    - cp framework/mvn-settings.xml /root/.m2/settings.xml
      # set the path inside of source tree so CI can cache it
      # see https://gitlab.com/gitlab-org/gitlab-ce/issues/4431
    - export MAVEN_OPTS=-Dmaven.repo.local=.mvnrepo
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - .mvnrepo
  script:
  - mvn -f framework/pom.xml -P coverage -DREDIS_SERVER=redis:6379 test jacoco:report
  - "cp -a framework/target/site/jacoco/ coverage && echo Coverage: `grep -o '[0-9]*%' coverage/index.html | head -1` || echo Coverage: 0%"
  artifacts:
    paths:
      - coverage/
    reports:
      junit:
        - framework/target/surefire-reports/TEST-*.xml
    expire_in: 2 weeks

deploy-dev: &deploy-dev
  stage: deploy
  tags:
    - u176i108
  variables:
    DOCKER_HOST_IP: 16.19.176.108
  environment: &u176i108
    name: u176i108
    url: http://16.19.176.108:3000/d/E_KTP6lmk/monitoring
    on_stop: stop-dev
  script:
    - (cd demo && docker-compose up --build --remove-orphans --detach)
  except:
    - master

stop-dev:
  <<: *deploy-dev
  variables:
    GIT_STRATEGY: none
  environment:
    <<: *u176i108
    action: stop
  script:
    - (cd demo && docker-compose down --remove-orphans)
  when: manual

deploy-master: &deploy-master
  stage: deploy
  tags:
    - u176i109
  variables:
    DOCKER_HOST_IP: 16.19.176.109
  environment: &u176i109
    name: u176i109
    url: http://16.19.176.109:3000/d/E_KTP6lmk/monitoring
  script:
    - (cd demo && docker-compose down --remove-orphans && docker-compose up --build --detach)
  only:
    - master