variables:
  http_proxy: "http://web-proxy.bbn.hpecorp.net:8080"
  https_proxy: "http://web-proxy.bbn.hpecorp.net:8080"

stages:
  - test
  - deploy

test-framework:
  stage: test
  image: maven:3.6.0-jdk-8
  services:
  - redis:5.0.3
  before_script:
    # proxy settings
    - "host=`echo $https_proxy | cut -d: -f2 | cut -d/ -f3`"
    - "port=`echo $https_proxy | cut -d: -f3`"
    # set the path inside of source tree so CI can cache it
    # see https://gitlab.com/gitlab-org/gitlab-ce/issues/4431
    - export MAVEN_OPTS="-Dmaven.repo.local=.mvnrepo -Dhttps.proxyHost=$host -Dhttps.proxyPort=$port"
    - echo $MAVEN_OPTS
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - .mvnrepo
  script:
  - mvn -f framework/pom.xml -P coverage -DREDIS_SERVER=redis:6379 test jacoco:report
  - "cp -a framework/target/site/jacoco/ coverage && echo Coverage: `grep -o '[0-9]*%' coverage/index.html | head -1` || echo Coverage: 0%"
  only:
    changes:
     - "framework/**/*"
  artifacts:
    paths:
      - coverage/
    reports:
      junit:
        - framework/target/surefire-reports/TEST-*.xml
    expire_in: 2 weeks

deploy-dev: &deploy-dev
  stage: deploy
  tags:
    - u176i108
  environment: &u176i108
    name: u176i108
    url: http://16.19.176.108:3000/d/E_KTP6lmk/monitoring
    on_stop: stop-dev
  dependencies: []
  script:
    - sed "s/__HOST__/`hostname`/g" playbooks/hosts-CI > playbooks/hosts
    - bash -x playbooks/setup.sh -sarbd
  except:
    - master

stop-dev:
  <<: *deploy-dev
  variables:
    GIT_STRATEGY: none
  environment:
    <<: *u176i108
    action: stop
  dependencies: []
  script:
    - bash -x playbooks/setup.sh -s
  when: manual

deploy-master: &deploy-master
  stage: deploy
  tags:
    - u176i109
  environment: &u176i109
    name: u176i109
    url: http://16.19.176.109:3000/d/E_KTP6lmk/monitoring
  dependencies: []
  script:
    - sed "s/__HOST__/`hostname`/g" playbooks/hosts-CI > playbooks/hosts
    - bash -x playbooks/setup.sh -sarbd
  only:
    - master
