stages:
  - deploy

deploy-demo-u176i108: &demo-u176i108
  stage: deploy
  tags:
    - u176i108
  variables:
    DOCKER_HOST_IP: 16.19.176.108
    PUBLIC_IP: 16.19.176.108
  environment: &u176i108
    name: u176i108
    url: http://16.19.176.108:39000/
    on_stop: stop-demo-u176i108
  script:
    - (cd demo && docker-compose up --build --remove-orphans --detach)

stop-demo-u176i108:
  <<: *demo-u176i108
  variables:
    GIT_STRATEGY: none
  environment:
    <<: *u176i108
    action: stop
  script:
    - (cd demo && docker-compose down)
  when: manual
