#
# Docker Compose with the following services:
#  collectd
#
# No hostname is asserted. We want the docker host's name for this container

version: '3'
services:
  collectd:
    build:
      context: collectd
      dockerfile: Dockerfile
    depends_on:
      - broker-1
      - broker-2
      - broker-3
