version: '3.4'
x-proxy: &proxy
  build:
    args:
      http_proxy: http://web-proxy.bbn.hpecorp.net:8080
      https_proxy: http://web-proxy.bbn.hpecorp.net:8080

services:
  connect:
    <<: *proxy

  broker-1:
    <<: *proxy

  broker-2:
    <<: *proxy

  broker-3:
    <<: *proxy
  
  simulator:
    <<: *proxy
 
  framework:
    build:
      args:
         http_proxy: http://web-proxy.bbn.hpecorp.net:8080
         https_proxy: http://web-proxy.bbn.hpecorp.net:8080
         MAVEN_OPTS: -Dhttps.proxyHost=web-proxy.bbn.hpecorp.net -Dhttps.proxyPort=8080

  druid:
    <<: *proxy

  grafana:
    <<: *proxy

  kafka-embedded-client-1:
    <<: *proxy

  mousttic-1:
    <<: *proxy

  test-tools:
    <<: *proxy

  collectd:
    <<: *proxy

  datapipes-monitor:
    <<: *proxy

  zookeeper:
    <<: *proxy

  schemaregistry:
    <<: *proxy

