version: '3.4'
x-proxy: &proxy
  build:
    args:
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}

services:
  broker-1:
    <<: *proxy

  broker-2:
    <<: *proxy

  broker-3:
    <<: *proxy
  
  fanin:
    <<: *proxy
 
  framework:
    build:
      args:
         http_proxy: ${http_proxy}
         https_proxy: ${https_proxy}
         MAVEN_OPTS: -Dhttps.proxyHost=web-proxy.bbn.hpecorp.net -Dhttps.proxyPort=8080

  druid:
    <<: *proxy

  grafana:
    <<: *proxy

  test-tools:
    <<: *proxy

  zookeeper:
    <<: *proxy

  schemaregistry:
    <<: *proxy

  config-zookeeper:
    <<: *proxy

  config-schemaregistry:
    <<: *proxy

  config-druid:
    <<: *proxy

  config-kafka:
    <<: *proxy

  mosquitto:
    <<: *proxy

  simulator:
    <<: *proxy
