version: '3.4'

secrets:
  km-ca-1.crt:
     file: ~/km-secrets/km-ca-1.crt
  km-ca-1.key:
     file: ~/km-secrets/km-ca-1.key
  km-ca-1.srl:
     file: ~/km-secrets/km-ca-1.srl
  broker-1-ca1-signed.crt:
     file: ~/km-secrets/broker-1-ca1-signed.crt
  broker-1.certificate.pem:
     file: ~/km-secrets/broker-1.certificate.pem
  broker-1.csr:
     file: ~/km-secrets/broker-1.csr
  broker-1.der:
     file: ~/km-secrets/broker-1.der
  broker-1.key:
     file: ~/km-secrets/broker-1.key
  broker-1.keystore.p12:
     file: ~/km-secrets/broker-1.keystore.p12
  broker-1_keystore_creds:
     file: ~/km-secrets/broker-1_keystore_creds
  broker-1_sslkey_creds:
     file: ~/km-secrets/broker-1_sslkey_creds
  broker-1_truststore_creds:
     file: ~/km-secrets/broker-1_truststore_creds
  broker-2-ca1-signed.crt:
     file: ~/km-secrets/broker-2-ca1-signed.crt
  broker-2.certificate.pem:
     file: ~/km-secrets/broker-2.certificate.pem
  broker-2.csr:
     file: ~/km-secrets/broker-2.csr
  broker-2.der:
     file: ~/km-secrets/broker-2.der
  broker-2.key:
     file: ~/km-secrets/broker-2.key
  broker-2.keystore.p12:
     file: ~/km-secrets/broker-2.keystore.p12
  broker-2_keystore_creds:
     file: ~/km-secrets/broker-2_keystore_creds
  broker-2_sslkey_creds:
     file: ~/km-secrets/broker-2_sslkey_creds
  broker-2_truststore_creds:
     file: ~/km-secrets/broker-2_truststore_creds
  broker-3-ca1-signed.crt:
     file: ~/km-secrets/broker-3-ca1-signed.crt
  broker-3.certificate.pem:
     file: ~/km-secrets/broker-3.certificate.pem
  broker-3.csr:
     file: ~/km-secrets/broker-3.csr
  broker-3.der:
     file: ~/km-secrets/broker-3.der
  broker-3.key:
     file: ~/km-secrets/broker-3.key
  broker-3.keystore.p12:
     file: ~/km-secrets/broker-3.keystore.p12
  broker-3_keystore_creds:
     file: ~/km-secrets/broker-3_keystore_creds
  broker-3_sslkey_creds:
     file: ~/km-secrets/broker-3_sslkey_creds
  broker-3_truststore_creds:
     file: ~/km-secrets/broker-3_truststore_creds
  broker_jaas.conf:
     file: ~/km-secrets/broker_jaas.conf
  client-ca1-signed.crt:
     file: ~/km-secrets/client-ca1-signed.crt
  client.certificate.pem:
     file: ~/km-secrets/client.certificate.pem
  client.csr:
     file: ~/km-secrets/client.csr
  client.der:
     file: ~/km-secrets/client.der
  client.key:
     file: ~/km-secrets/client.key
  client.keystore.p12:
     file: ~/km-secrets/client.keystore.p12
  client_keystore_creds:
     file: ~/km-secrets/client_keystore_creds
  client_sslkey_creds:
     file: ~/km-secrets/client_sslkey_creds
  client_truststore_creds:
     file: ~/km-secrets/client_truststore_creds
  kafka.broker-1.keystore.pfx:
     file: ~/km-secrets/kafka.broker-1.keystore.pfx
  kafka.broker-1.truststore.pfx:
     file: ~/km-secrets/kafka.broker-1.truststore.pfx
  kafka.broker-2.keystore.pfx:
     file: ~/km-secrets/kafka.broker-2.keystore.pfx
  kafka.broker-2.truststore.pfx:
     file: ~/km-secrets/kafka.broker-2.truststore.pfx
  kafka.broker-3.keystore.pfx:
     file: ~/km-secrets/kafka.broker-3.keystore.pfx
  kafka.broker-3.truststore.pfx:
     file: ~/km-secrets/kafka.broker-3.truststore.pfx
  kafka.client.keystore.pfx:
     file: ~/km-secrets/kafka.client.keystore.pfx
  kafka.client.truststore.pfx:
     file: ~/km-secrets/kafka.client.truststore.pfx
  kafka.schemaregistry.keystore.pfx:
     file: ~/km-secrets/kafka.schemaregistry.keystore.pfx
  kafka.schemaregistry.truststore.pfx:
     file: ~/km-secrets/kafka.schemaregistry.truststore.pfx
  schemaregistry-ca1-signed.crt:
     file: ~/km-secrets/schemaregistry-ca1-signed.crt
  schemaregistry.certificate.pem:
     file: ~/km-secrets/schemaregistry.certificate.pem
  schemaregistry.csr:
     file: ~/km-secrets/schemaregistry.csr
  schemaregistry.der:
     file: ~/km-secrets/schemaregistry.der
  schemaregistry.key:
     file: ~/km-secrets/schemaregistry.key
  schemaregistry.keystore.p12:
     file: ~/km-secrets/schemaregistry.keystore.p12
  schemaregistry_keystore_creds:
     file: ~/km-secrets/schemaregistry_keystore_creds
  schemaregistry_sslkey_creds:
     file: ~/km-secrets/schemaregistry_sslkey_creds
  schemaregistry_truststore_creds:
     file: ~/km-secrets/schemaregistry_truststore_creds
  zookeeper_jaas.conf:
     file: ~/km-secrets/zookeeper_jaas.conf
  client-sasl_ssl.conf:
     file: ~/km-secrets/client-sasl_ssl.conf
  kafka.mosquittosecu.keystore.pfx:
     file: ~/km-secrets/kafka.mosquittosecu.keystore.pfx
  kafka.mosquittosecu.truststore.pfx:
     file: ~/km-secrets/kafka.mosquittosecu.truststore.pfx
  mosquittosecu-ca1-signed.crt:
     file: ~/km-secrets/mosquittosecu-ca1-signed.crt
  mosquittosecu.certificate.pem:
     file: ~/km-secrets/mosquittosecu.certificate.pem
  mosquittosecu.csr:
     file: ~/km-secrets/mosquittosecu.csr
  mosquittosecu.der:
     file: ~/km-secrets/mosquittosecu.der
  mosquittosecu.key:
     file: ~/km-secrets/mosquittosecu.key
  mosquittosecu.keystore.p12:
     file: ~/km-secrets/mosquittosecu.keystore.p12
  mosquittosecu_keystore_creds:
     file: ~/km-secrets/mosquittosecu_keystore_creds
  mosquittosecu_sslkey_creds:
     file: ~/km-secrets/mosquittosecu_sslkey_creds
  mosquittosecu_truststore_creds:
     file: ~/km-secrets/mosquittosecu_truststore_creds

