# https://github.com/toml-lang/toml - https://github.com/avakar/pytoml
title = "Config file for kafka listener"

refresh_period_sec  = 29

[kafka_server]
hosts       = [ "broker-1:9092" ]
agent_id    = "datapipesmonitor"
agent_grpid = "datapipesmonitor"

[outputs]
directory_for_json = "./www"

[influxdb]
ip          = "influxdb"
port        = 8086
username    = ""
password    = ""
dbdefault   = "datapipes"
timeout     = 15

