# https://github.com/toml-lang/toml - https://github.com/avakar/pytoml
title = "Config MQTT Listener"

refresh_period_sec  = 29

[system_topics_to_influx]
enable              = true

[topics_full_hierarchy_by_filters]
filters_for_topics                  = [ "registration/#" , "device-registration/#" , "ibswitch/#" , "test/#" ]
enable_message_rates_to_influx      = true
enable_message_rates_to_webserv     = false
directory_for_json                  = "./www"
deepness_max_level                  = 9
enable_last_seen_message_to_influx  = true
hourstoforget                       = 72.0 # in hours, no msg on a topic for this duration = topic is forgotten from reports

[mqtt_server]
host      = "mosquitto"     # Name or IP
port      = 8883            # integer
keepalive = 30
ca_certs  = "/run/secrets/km-ca-1.crt"
certfile  = "/run/secrets/mosquitto.certificate.pem"
keyfile   = "/run/secrets/mosquitto.key"

[influxdb]
ip          = "influxdb"
port        = 8086
username    = ""
password    = ""
dbdefault   = "datapipes"
timeout     = 15
