#
# Docker Compose with the following services:
#  mosquitto
#  simulator
#  druid
#  grafana
#

version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    hostname: mosquitto
    ports: 
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  simulator:
    build:
      context: simulator
      dockerfile: Dockerfile
    hostname: simulator
    depends_on:
      - mosquitto
    environment:
      MOSQUITTO_IP: '${DOCKER_HOST_IP}'

  druid:
    build:
      context: druid
      dockerfile: Dockerfile
    hostname: druid
    depends_on:
      - zookeeper
    ports:
# - 8081: HTTP (coordinator)
# - 8082: HTTP (broker)
# - 8083: HTTP (historical)
# - 8090: HTTP (overlord)
# - 3306: MySQL
      - "8181:8081"
      - "8182:8082"
      - "8183:8083"
      - "8190:8090"
      - "8200:8200"
      - "3306:3306"
      - "9095:9095"
      - "1527:1527"

  grafana:
    image: grafana/grafana
    hostname: grafana
    depends_on:
      - druid
    ports:
      - "3000:3000"
    volumes:
    - ./grafana/provisioning/:/etc/grafana/provisioning
    - ./grafana/dashboards/:/etc/grafana/dashboards
    - ./grafana/plugins/:/var/lib/grafana/plugins/
