#
# Docker Compose with the following services:
#  mosquitto
#  simulator
#  influxdb
#  grafana
#

version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    hostname: mosquitto
    ports: 
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  simulator:
    build:
      context: simulator
      dockerfile: Dockerfile
    hostname: simulator
    depends_on:
      - mosquitto
    environment:
      MOSQUITTO_IP: '${DOCKER_HOST_IP}'
    restart: always

  influxdb:
    image: influxdb
    hostname: influxdb
    ports:
      - "8086:8086"
    restart: always

  grafana:
    image: grafana/grafana
    hostname: grafana
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    volumes:
    - ./grafana/provisioning/:/etc/grafana/provisioning
    - ./grafana/dashboards/:/etc/grafana/dashboards
    restart: always
