#
# Docker Compose with the following services:
#  mosquitto
#  simulator
#  druid
#  grafana
#

version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    hostname: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  test-tools:
    build:
      context: test-tools
      dockerfile: Dockerfile
    hostname: test
    depends_on:
      - mosquitto
      - kafka-embedded-client-1
    environment:
      MOSQUITTO_IP: mosquitto
      KAFKA_BROKER_IP: broker-1

  simulator:
    build:
      context: simulator
      dockerfile: Dockerfile
    hostname: simulator
    depends_on:
      - framework
      - connect
      - mosquitto

  kafka-embedded-client-1:
    build:
      context: ../kafka-client
      dockerfile: Dockerfile
    hostname: kafka-emb1
    depends_on:
      - broker-1
    environment:
      KAFKA_BROKER_IP: broker-1
      restart: always

  mousttic-1:
    build:
      context: ../mousttic
      dockerfile: Dockerfile
    hostname: mousttic-1
    depends_on:
      - mosquitto
    environment:
      MOSQUITTO_IP: mosquitto
    restart: always

  kafka-embedded-client-1:
    build:
      context: ../kafka-client
      dockerfile: Dockerfile
    hostname: kafka-emb1
    depends_on:
      - broker-1
    environment:
      KAFKA_BROKER_IP: broker-1
      restart: always

  mousttic-1:
    build:
      context: ../mousttic
      dockerfile: Dockerfile
    hostname: mousttic-1
    depends_on:
      - mosquitto
    environment:
      MOSQUITTO_IP: mosquitto
    restart: always

  druid:
    build:
      context: druid
      dockerfile: Dockerfile
    hostname: druid
    depends_on:
      - zookeeper
    ports:
# - 8081: HTTP (coordinator)
# - 8082: HTTP (broker)
# - 8083: HTTP (historical)
# - 8090: HTTP (overlord)
# - 3306: MySQL
      - "8181:8081"
      - "8182:8082"
      - "8183:8083"
      - "8190:8090"
      - "8200:8200"
      - "3306:3306"
      - "9095:9095"
      - "1527:1527"

  grafana:
    image: grafana/grafana
    hostname: grafana
    depends_on:
      - druid
    ports:
      - "3000:3000"
    volumes:
    - ./grafana/provisioning/:/etc/grafana/provisioning
    - ./grafana/dashboards/:/etc/grafana/dashboards
    - ./grafana/plugins/:/var/lib/grafana/plugins/
