---
- name: Start Docker Registry
  hosts: registry
  # gather_facts: no

  vars_files:
    - vars.yml

  environment:
    http_proxy: "{{ proxy }}"
    https_proxy: "{{ proxy }}"


  tasks:

    - name: Copy docker-compose.yml
      copy:
        src: /docker-registry/
        dest: /tmp/docker-registry/

    #docker_compose ( or docker_service ) module not allow us to specify multiple file (June 21 2019)
    - name: Use docker-compose
      shell: docker-compose -f /tmp/docker-registry/mirror-registry.yml -f /tmp/docker-registry/docker-proxy.yml up -d
      register: output

    - name: Debug of docker-compose
      debug:
        var: output
