- name: Remove all workers from Swarm
  hosts: swarm_nodes,swarm_manager

  vars_files:
    - vars.yml
  environment:
    http_proxy: "{{ proxy }}"
    https_proxy: "{{ proxy }}"

  tasks:

    - name: Remove nodes
      docker_swarm:
        state: absent    
        force: true
